# Configuracion de correo
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: testingcanchas@gmail.com
    password: Procanchas2018
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
    protocol: smtp
    test-connection: false

